import {Medico} from './Medicos'

export const MEDICOS: Medico[]=[{
    id: 1,
    Nombre: 'Pedro Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css Using a pre-built theme Angular Material comes files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'One', cols: 3, rows: 1, color: 'lightblue',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes Using a pre-built theme Angular Material comes Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Three', cols: 1, rows: 1, color: 'lightpink',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  }, 
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    Nombre: 'Juan Medico',
    descripcion: 'Using a pre-built theme Angular Material comes prepackaged with several pre-built theme css files. These theme files also include all of the styles for core (styles common to all components), so you only have to include a single css file for Angular Material in your app.You can include a theme file directly into your application from @angular/material/prebuilt-themes Available pre-built themes',
    categoria:  'medico general',
    Numero_turnos: 5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    text: 'Four', cols: 2, rows: 1, color: '#DDBDF1',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  ];
