import {Medico} from './Medicos'

export const MEDICOS: Medico[]=[{
    id: 1,
    turnos: 23,
    Nombre: 'Pedro ramires Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos: 23,
    Nombre: 'Usuario Odontologo',
    categoria:  'Odontolo',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 3,
    votos: 1500,
    Total_puntos: 4500,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 3,
    turnos:33,
    Nombre: 'Escobar Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 4,
    turnos: 32,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 3,
    votos: 1500,
    Total_puntos: 4500,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 5,
    turnos: 32,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 6,
    turnos: 9,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 7,
    turnos: 10,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos:23,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos:23,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos:23,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos:23,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
  {
    id: 2,
    turnos:23,
    Nombre: 'Juan Medico',
    categoria:  'medico general',
    Numero_turnos: 4.5,
    foto: 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_Circle.png',
    rankin: 4,
    votos: 1500,
    Total_puntos: 6000,
    text: 'Two', cols: 1, rows: 2, color: 'lightgreen',
    numero_de_votos: '5: star vt:2o 4 Start: 5vt',
  },
];
